# Generated by Django 4.1.7 on 2023-04-05 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('actor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actor')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='industry_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.industry'),
        ),
    ]
