# Generated by Django 4.1.7 on 2023-04-07 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actor')),
            ],
        ),
    ]
